import { DELETE } from "~/config/constant"

const API = {
  CATEGORIES: 'category',
  TAGS: 'tag',
  COURSE: 'course',
  COURSE_LEARN: 'course/:course_slug/learn',
  COURSES: 'courses',
  LESSON: 'lesson',
  LESSONS_BY_COURSE_SLUG: 'lessons/by-course-slug',
  FAQ: '/faq',
  LESSONS_COMPLETE: '/lesson/complete',
  USER_DETAIL: '/user/profile',
  UPLOAD_AVATAR_USER: '/user/avatar',
  UPDATE_USER: '/user/profile',
  USER_LOGOUT: 'user/logout',
  USER_NOTIFICATIONS: '/user/notifications',
  USER_NOTIFICATION_READ: '/user/notifications/read/:id',
  USER_NOTIFICATION_READ_ALL: '/user/notifications/read-all',
  USER_NOTIFICATION_UNREAD_COUNT: '/user/notifications/unread-count',
  USER_COURSES: '/user/my-courses',
  GENERATE_CERTIFICATE: '/user/generate-certificate',
  COMMENT : '/comment',
  GET_COMMENT_BY_SLUG: '/comment/get-by-lesson-slug',
  GET_COMMENT_BY_ID: '/comment/get-by-id',
  UPDATE_COMMENT: '/comment/update',
  DELETE_COMMENT: '/comment/delete',
  RESOURCES:'/resources',
  NEWS: '/news',
  GET_LIST_SETTING_HOME: '/setting-home',
  TESTUMONIAL:'/testimonial',
  COUNT_DATA: '/count-data',
  SEARCH: 'search',
  CONTACTS: 'contacts',
  ARTICLES: 'articles',
  DETAIL_ARTICLE: 'articles/:slug',
  ARTICLES_GET_BY_CATEGORY_ID: 'articles/category/:id',
}
export default API
